### ISSUE TITLE
TransactionTooLargeException lost:2.1.2

### ISSUE THREAD

**Issue by lidkxx** [lostzen/lost#223]
### Description
Getting a Runtime Exception and app crashes with the following log (taken from Google Play Console):

`java.lang.RuntimeException: 
  at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java:78)
  at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:196)
  at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:286)
  at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:215)
  at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:238)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:6934)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: android.os.TransactionTooLargeException: 
  at android.os.BinderProxy.transactNative(Native Method:0)
  at android.os.BinderProxy.transact(Binder.java:496)
  at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(IFusedLocationProviderCallback.java:104)
  at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java:76)`

### Steps to Reproduce
Not able to reproduce so far. Will update as soon as we're able to track it again.

### Lost & Android Version
Lost: `com.mapzen.android:lost:2.1.2` used by mapbox-android-sdk:5.0.2
Android 5.1, Samsung Galaxy J3(2016) (j3xnlte)

**Comment by 13kz** [comment]
@lidkxx Looks like #218 (**The DeadObject Exception**)

**Comment by msmollin** [comment]
@13kz it's definetly similar (and @lidkxx reported it first in there) - however it's throwing a different exception that #218 so I wanted to make sure it got tracked separately so it doesn't get lost in what is becoming a big thread in that other issue.

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
